### PR TITLE
add continous integration with the last intel compilers

### PR DESCRIPTION
**Pull request by dareg**
Downloads and install the last intel compilers from their official repository and run the field_api tests.

Note that it uses the new icx and ifx compilers instead of the old icc and ifort compilers.

### CODE REVIEW

**Comment by awnawab** [comment]
Happy new year @dareg and thanks for this much needed addition to the CI. We don't currently use ifx for ifs builds. Have you started using it? If you don't use it either, then perhaps it might be more useful to use ifort for the CI too. You can see an example here of how ifort rather than ifx can be installed: https://github.com/ecmwf-ifs/ecwam/blob/main/.github/tools/install-intel-oneapi.sh

**Comment by awnawab** [comment]
Testing with both ifort and ifx makes a lot of sense to me too, I'd be happy with that!

**Comment by awnawab** [comment]
Hi @dareg. I have to file a fix for the FIELD_API build and CI setup. Do you think we could wrap up this PR soon, and then I'll rebase my changes on top of yours?

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/field_api?pullRequest=17) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/field_api?pullRequest=17) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf-ifs/field_api?pullRequest=17) it.</sub>

**Comment by dareg** [comment]
Done.
I've added the tests with the classic intel compilers into their own file. Will be easy to remove them when we won't need them any more.

**Review by awnawab — APPROVED** [review]
Thanks a lot @dareg for adding both ifort and ifx CI tests 👍  Good to go from me!

**Pull request merged**
