### PR TITLE
Small fixes to `COPY_DATA`

### PR DESCRIPTION
**Pull request by awnawab**
This PR applies two small fixes to `COPY_DATA`:
- The use of the OpenACC runtime function `ACC_DEVICEPTR` in `COPY_DIM_CONTIGUOUS` is replaced with `acc host_data` to align it with `COPY_2D`
- The case of the fully contiguous field is promoted to the top of the nested `SELECT CASE`. This is the best possible scenario for data transfers and we should check this first rather than at the end.

The last point resulted in a more than 10% gain in data transfer speeds for CLOUDSC

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/field_api?pullRequest=22) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/field_api?pullRequest=22) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf-ifs/field_api?pullRequest=22) it.</sub>

**Comment by pmarguinaud** [comment]
So what you mean is that we are spending a lot of time in the nested SELECT CASE constructs ? If so, we should probably take some more radical action, like storing a pointer to the copy function in the object itself.

**Comment by awnawab** [comment]
Yes I think there was definitely an overhead for the nested `SELECT CASE` constructs. I really like your solution with determining the copy method at field construction time and storing a pointer to it, thanks so much for suggesting it 😄  Could I please merge that commit to this PR and test it?

**Comment by awnawab** [comment]
Hi @pmarguinaud,

I tested your `COPY_FUNC` fix and it indeed restores all the lost performance, thanks again for that! Could I please merge your `naan-copy-data-fix` branch to this PR? I need another small fix on top of that for transferring very large arrays. After that we can close this PR.

**Comment by awnawab** [comment]
Hi @pmarguinaud. Thanks again for contributing the fix. Could I please your contribution to this PR (and add another small commit on top) so we can close this soon?

**Comment by pmarguinaud** [comment]
Hello Ahmad,

Yes please merge my branch in your PR.

Regards

**Review by pmarguinaud — APPROVED** [review]

**Review by mlange05 — APPROVED** [review]
Looks good to me. Thanks both for fixing this!

**Pull request merged**
